name: 'PR Comment'
description: 'Post a comment on a pull request'
author: 'konuma'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  message:
    description: 'Message to comment'
    required: true
outputs:
  comment-url:
    description: 'The PR comment URL'

runs:
  using: node20
  main: dist/index.js
branding:
  icon: 'message-square'
  color: 'green'